### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by milutz** [cjhurst/Articulate_Translate#1]
If you have stuff thats needed beyond the base python libraries, can you please make a `requirements.txt` with them (and include the command to install them in your setup instructions)

This is what I got when I tried to run:
```
% git clone https://github.com/cjhurst/AgentConversionUtility.git 
Cloning into 'AgentConversionUtility'...
remote: Counting objects: 98, done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 98 (delta 36), reused 91 (delta 29), pack-reused 0
Unpacking objects: 100% (98/98), done.
% cd AgentConversionUtility 
% python -m agent_data_converter -h
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/milutz/src/python/AgentConversionUtility/agent_data_converter.py", line 1, in <module>
    import training_data as td
  File "training_data/__init__.py", line 8, in <module>
    from training_data.message import Message
  File "training_data/message.py", line 8, in <module>
    from utils import ordered
  File "utils/__init__.py", line 15, in <module>
    import simplejson
ImportError: No module named simplejson
```

(tryed in both python 2.7 and python 3.7 with same error

**Comment by cjhurst** [comment]
I added one, can you try it out?

**Comment by milutz** [comment]
Good stuff, checked it and it does the trick.  Thanks!
